version: '3.9'
name: "aledia"

services:

    frontend:
        image: alediafront
        restart: always
        build:
            context: ../../../frontend
            dockerfile: .cloud/docker/Dockerfile
        environment:
            BACKEND: http://localhost:9000
            NGINX_HOST: localhost
            TLS: false
        ports:
            - 666:80
            # - 443:443
        depends_on:
            - backend
        # secrets:
        #     - source: certificat
        #       target: certificat.crt
        #     - source: cle_certificat
        #       target: cle_certificat.key

    backend:
        image: alediaback
        restart: always
        depends_on:
            - postgres-aledia
        build:
            context: ../../../backend
            dockerfile: .cloud/docker/Dockerfile
        environment:
            DB_HOST: "postgres-aledia"
            DB_USER: "postgres"
            DB_PASSWORD: "coi1234"
            DB_NAME: "user_al"
            DB_DATA_NAME: "test_al"
            DB_DATA_TABLE_NAME: "split_history"
            DB_DIALECT: "postgres"
            DB_PORT: 5432
        ports:
            - 9000:3001
        volumes:
            - database-init:/usr/src/app/.cloud/sql_backup:ro

    postgres-aledia:
        image: postgres:alpine3.15
        environment:
            LANG: C.UTF-8
            POSTGRES_PASSWORD: "coi1234"
        ports:
            - "5433:5432"
        volumes:
            # - database-init:/docker-entrypoint-initdb.d
            - postgres-aledia-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:6.12
        container_name: pgadmin01
        environment:
            - PGADMIN_DEFAULT_EMAIL=coi-scd@outlook.com
            - PGADMIN_DEFAULT_PASSWORD=password
        volumes:
            - pgadmin-data:/var/lib/pgadmin/
        ports:
            - 8081:80

volumes:
    database-init:
    postgres-aledia-data:
    pgadmin-data:
# secrets:
#     # Certificat SSL
#     certificat:
#         file: ../config/localhost.pem
#     # Clé du certificat SSL
#     cle_certificat:
#         file: ../config/localhost-key.pem
